name: GeoSonarHunt
options:
  bundleIdPrefix: com.geosohunt
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  defaultConfig: Debug
  
configs:
  Debug: debug
  Release: release

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_SWIFT_TESTING: YES
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    # Release build optimizations
    SWIFT_COMPILATION_MODE: wholemodule
    SWIFT_OPTIMIZATION_LEVEL: "-O"
    GCC_OPTIMIZATION_LEVEL: "s"
    # Security settings
    ENABLE_BITCODE: NO
    VALIDATE_PRODUCT: YES
    # Code signing
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM_ID)"

targets:
  GeoSonarHuntApp:
    type: application
    platform: iOS
    sources: 
      - GeoSonarHuntApp
    dependencies:
      - package: GeoSonarCore
      - package: GeoSonarUI
    info:
      path: GeoSonarHuntApp/Info.plist
      properties:
        CFBundleDisplayName: "Geo Sonar Hunt"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        NSLocationWhenInUseUsageDescription: "このアプリは宝探しゲームで現在位置を使用します"
        UILaunchStoryboardName: LaunchScreen
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIRequiredDeviceCapabilities:
          - armv7
          - location-services
          - gps
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.geosohunt.app
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UIUserInterfaceStyle: Automatic
      Debug:
        CODE_SIGN_IDENTITY: "iPhone Developer"
        PROVISIONING_PROFILE_SPECIFIER: "$(APP_PROVISIONING_PROFILE_DEBUG)"
      Release:
        CODE_SIGN_IDENTITY: "iPhone Distribution"
        PROVISIONING_PROFILE_SPECIFIER: "$(APP_PROVISIONING_PROFILE_RELEASE)"
        # Release-specific optimizations
        SWIFT_COMPILATION_MODE: wholemodule
        SWIFT_OPTIMIZATION_LEVEL: "-O"
        GCC_OPTIMIZATION_LEVEL: "s"
        VALIDATE_PRODUCT: YES
        # Strip debug symbols in release
        STRIP_INSTALLED_PRODUCT: YES
        COPY_PHASE_STRIP: YES
        # Deployment settings
        SKIP_INSTALL: NO
        INSTALL_PATH: "/Applications"

  GeoSonarHuntAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/GeoSonarHuntAppTests
    dependencies:
      - target: GeoSonarHuntApp
      - package: GeoSonarCore
      - package: GeoSonarUI
      - package: GeoSonarTesting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.geosohunt.app.tests

  GeoSonarHuntAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - Tests/GeoSonarHuntAppUITests
    dependencies:
      - target: GeoSonarHuntApp
      - package: GeoSonarCore
      - package: GeoSonarUI
      - package: GeoSonarTesting
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.geosohunt.app.uitests
        TEST_TARGET_NAME: GeoSonarHuntApp

packages:
  GeoSonarCore:
    path: Packages/GeoSonarCore
  GeoSonarUI:
    path: Packages/GeoSonarUI
  GeoSonarTesting:
    path: Packages/GeoSonarTesting

schemes:
  GeoSonarHuntApp:
    build:
      targets:
        GeoSonarHuntApp: all
        GeoSonarHuntAppTests: [test]
        GeoSonarHuntAppUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: GeoSonarHuntAppTests
          parallelizable: true
        - name: GeoSonarHuntAppUITests
          parallelizable: false
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release