name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
      
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show Swift version
      run: swift --version
      
    - name: Install XcodeGen
      run: |
        brew install xcodegen
        
    - name: Generate Xcode project
      run: xcodegen generate
      
    - name: Build and test GeoSonarCore
      run: |
        cd Packages/GeoSonarCore
        swift test --enable-code-coverage
        
    - name: Build and test GeoSonarUI
      run: |
        cd Packages/GeoSonarUI
        swift test --enable-code-coverage
        
    - name: Build and test GeoSonarTesting
      run: |
        cd Packages/GeoSonarTesting
        swift test --enable-code-coverage
        
    - name: Build main app
      run: |
        xcodebuild build \
          -project GeoSonarHunt.xcodeproj \
          -scheme GeoSonarHuntApp \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Run app tests
      run: |
        xcodebuild test \
          -project GeoSonarHunt.xcodeproj \
          -scheme GeoSonarHuntApp \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
          CODE_SIGNING_ALLOWED=NO

  lint:
    name: SwiftLint
    runs-on: macos-14
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging